# Generated by Django 5.2.4 on 2025-08-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='thumbnails_images')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('customer', models.CharField(max_length=75)),
                ('category', models.CharField(max_length=75)),
                ('tech', models.CharField(max_length=120)),
                ('project_url', models.CharField(max_length=150)),
                ('picture1', models.ImageField(upload_to='pictures_images')),
                ('picture2', models.ImageField(upload_to='pictures_images')),
                ('picture3', models.ImageField(upload_to='pictures_images')),
                ('picture4', models.ImageField(upload_to='pictures_images')),
            ],
        ),
    ]
