# Generated by Django 5.2.4 on 2025-08-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.CharField(default=1, max_length=75),
            preserve_default=False,
        ),
    ]
